name: Build Website

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v2

    - name: Download pandoc
      uses: robinraju/release-downloader@v1.5
      with:
        repository: "jgm/pandoc"
        latest: true
        fileName: "pandoc-*-amd64.deb"

    - name: Install pandoc
      run: |
        sudo dpkg -i pandoc-*-amd64.deb &&
        sudo apt install -f -y

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r docs/requirements.txt

    - name: Build the website
      run: make docs-ci

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./docs/build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1